USE ROLE SRS_SYSTEM_ADMIN;
USE DATABASE ADMIN;
USE SCHEMA RBAC;

CREATE OR REPLACE PROCEDURE TEST_IF(P_NAME VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
BEGIN
    IF P_NAME IS NULL THEN
        RETURN 'NULL';
    END IF;
    RETURN 'OK';
END;
$$;
